SELECT
    BUKRS AS company_code,
    LIFNR AS vendor_number,
    GJAHR AS fiscal_year,
    BELNR AS accounting_document,
    BUZEI AS line_item,
    BUDAT AS posting_date,
    BLDAT AS document_date,
    WAERS AS document_currency,
    XBLNR AS reference_document,
    BLART AS document_type,
    MONAT AS fiscal_period,
    BSCHL AS posting_key,
    HKONT AS gl_account,
    SHKZG AS debit_credit_indicator,
    DMBTR AS amount_local_currency,
    WRBTR AS amount_document_currency,
    MWSKZ AS tax_code,
    GSBER AS business_area,
    KOSTL AS cost_center,
    PRCTR AS profit_center,
    ZTERM AS payment_terms,
    SGTXT AS item_text,
    ZFBDT AS baseline_payment_date,
    AUGDT AS clearing_date,
    AUGBL AS clearing_document,
    AUGDT_CLEAR AS payment_date,
    'CLEARED' AS item_status
FROM {{ source('sap', 'BSAK') }}
WHERE MANDT = '100'
