SELECT
    VBELN AS sales_document,
    POSNR AS item_number,
    MATNR AS material_number,
    ARKTX AS item_description,
    PSTYV AS item_category,
    NETWR AS net_value,
    WAERK AS document_currency,
    NETPR AS net_price,
    KPEIN AS pricing_unit,
    KWMENG AS order_quantity,
    VRKME AS sales_unit,
    WERKS AS plant,
    LGORT AS storage_location,
    VSTEL AS shipping_point,
    ROUTE AS route,
    ERDAT AS created_date,
    ERNAM AS created_by,
    AEDAT AS last_changed_date,
    ABGRU AS rejection_reason,
    MATKL AS material_group,
    PRODH AS product_hierarchy,
    NTGEW AS net_weight,
    BRGEW AS gross_weight,
    GEWEI AS weight_unit,
    MVGR1 AS material_group_1,
    MVGR2 AS material_group_2,
    VGBEL AS reference_document,
    VGPOS AS reference_item,
    GSBER AS business_area
FROM {{ source('sap', 'VBAP') }}
WHERE MANDT = '100'
