SELECT
    VBELN AS sales_document,
    ERDAT AS created_date,
    ERNAM AS created_by,
    AUDAT AS document_date,
    VBTYP AS document_category,
    AUART AS document_type,
    AUGRU AS order_reason,
    NETWR AS net_value,
    WAERK AS document_currency,
    VKORG AS sales_organization,
    VTWEG AS distribution_channel,
    SPART AS division,
    VKBUR AS sales_office,
    VKGRP AS sales_group,
    KUNNR AS sold_to_party,
    VDATU AS requested_delivery_date,
    AUTLF AS complete_delivery_flag,
    VSBED AS shipping_conditions,
    BSTNK AS purchase_order_number,
    BSTDK AS purchase_order_date,
    INCO1 AS incoterms_1,
    INCO2 AS incoterms_2,
    ZTERM AS payment_terms,
    BUKRS_VF AS billing_company_code,
    KNUMV AS pricing_document,
    AEDAT AS last_changed_date,
    LIFSK AS delivery_block,
    FAKSK AS billing_block
FROM {{ source('sap', 'VBAK') }}
WHERE MANDT = '100'
