SELECT
    VBELN AS billing_document,
    FKART AS billing_type,
    FKTYP AS billing_category,
    VBTYP AS document_category,
    WAERK AS document_currency,
    VKORG AS sales_organization,
    VTWEG AS distribution_channel,
    SPART AS division,
    FKDAT AS billing_date,
    ERDAT AS created_date,
    ERNAM AS created_by,
    BUKRS AS company_code,
    NETWR AS net_value,
    MWSBK AS tax_amount,
    KUNRG AS payer,
    KUNAG AS sold_to_party,
    INCO1 AS incoterms_1,
    INCO2 AS incoterms_2,
    ZTERM AS payment_terms,
    GJAHR AS fiscal_year,
    BELNR AS accounting_document,
    XBLNR AS reference_document,
    FKSTO AS cancelled_flag,
    LAND1 AS country_key,
    KURRF AS exchange_rate,
    AEDAT AS last_changed_date
FROM {{ source('sap', 'VBRK') }}
WHERE MANDT = '100'
