SELECT
    VBELN AS billing_document,
    POSNR AS item_number,
    FKIMG AS billed_quantity,
    VRKME AS sales_unit,
    NETWR AS net_value,
    MWSBP AS tax_amount,
    MATNR AS material_number,
    ARKTX AS item_description,
    PSTYV AS item_category,
    WERKS AS plant,
    LGORT AS storage_location,
    MATKL AS material_group,
    PRODH AS product_hierarchy,
    VGBEL AS reference_document,
    VGPOS AS reference_item,
    AUBEL AS sales_order,
    AUPOS AS sales_order_item,
    ERDAT AS created_date,
    GSBER AS business_area,
    PRCTR AS profit_center,
    KOSTL AS cost_center,
    KZWI1 AS subtotal_1,
    KZWI2 AS subtotal_2,
    KZWI3 AS subtotal_3,
    WAVWR AS cost_value
FROM {{ source('sap', 'VBRP') }}
WHERE MANDT = '100'
