SELECT
    KUNNR AS customer_number,
    LAND1 AS country_key,
    NAME1 AS customer_name,
    NAME2 AS customer_name_2,
    ORT01 AS city,
    PSTLZ AS postal_code,
    REGIO AS region,
    SORTL AS sort_field,
    STRAS AS street,
    TELF1 AS telephone,
    TELFX AS fax,
    ADRNR AS address_number,
    ANRED AS title,
    BRSCH AS industry_key,
    ERDAT AS created_date,
    ERNAM AS created_by,
    KTOKD AS account_group,
    SPRAS AS language_key,
    STCD1 AS tax_number_1,
    STCD2 AS tax_number_2,
    STCEG AS vat_registration_no,
    LZONE AS transport_zone,
    KUKLA AS customer_classification,
    LIFNR AS vendor_number,
    LOEVM AS deletion_flag,
    SPERR AS central_posting_block,
    KONZS AS group_key
FROM {{ source('sap', 'KNA1') }}
WHERE MANDT = '100'