SELECT
    BUKRS AS company_code,
    BELNR AS accounting_document,
    GJAHR AS fiscal_year,
    BUZEI AS line_item,
    BSCHL AS posting_key,
    SHKZG AS debit_credit_indicator,
    GSBER AS business_area,
    HKONT AS gl_account,
    DMBTR AS amount_local_currency,
    WRBTR AS amount_document_currency,
    MWSKZ AS tax_code,
    KOSTL AS cost_center,
    PRCTR AS profit_center,
    AUFNR AS order_number,
    KUNNR AS customer_number,
    LIFNR AS vendor_number,
    VBELN AS sales_document,
    EBELN AS purchase_order,
    MATNR AS material_number,
    WERKS AS plant,
    MENGE AS quantity,
    MEINS AS unit_of_measure,
    SGTXT AS item_text,
    ZTERM AS payment_terms,
    ZLSCH AS payment_method,
    ZBD1T AS discount_days_1,
    ZBD2T AS discount_days_2,
    ZBD3T AS net_payment_days,
    ZBD1P AS discount_percent_1,
    VALUT AS value_date,
    ZFBDT AS baseline_payment_date,
    AUGDT AS clearing_date,
    AUGBL AS clearing_document,
    SEGMENT AS segment,
    XBLNR AS reference_key
FROM {{ source('sap', 'BSEG') }}
WHERE MANDT = '100'
