SELECT
    BUKRS AS company_code,
    LIFNR AS vendor_number,
    GJAHR AS fiscal_year,
    BELNR AS accounting_document,
    BUZEI AS line_item,
    BUDAT AS posting_date,
    BLDAT AS document_date,
    WAERS AS document_currency,
    XBLNR AS reference_document,
    BLART AS document_type,
    MONAT AS fiscal_period,
    BSCHL AS posting_key,
    HKONT AS gl_account,
    SHKZG AS debit_credit_indicator,
    DMBTR AS amount_local_currency,
    WRBTR AS amount_document_currency,
    MWSKZ AS tax_code,
    GSBER AS business_area,
    KOSTL AS cost_center,
    PRCTR AS profit_center,
    ZTERM AS payment_terms,
    SGTXT AS item_text,
    ZFBDT AS baseline_payment_date,
    ZLSCH AS payment_method,
    ZBD1T AS discount_days_1,
    ZBD3T AS net_payment_days,
    ZBD1P AS discount_percent_1,
    'OPEN' AS item_status
FROM {{ source('sap', 'BSIK') }}
WHERE MANDT = '100'